'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {windowScore,forecastConfidence,tripWindow,decision} from '@/lib/window-decision';
import {calendarLink} from '@/lib/window-calendar';
import CalendarPanel from '@/components/calendar-panel';

type Place={id:string;name:string;region:string;lat:number;lon:number};
const STORAGE='window-demo-places-v1';
const minutes=(s:string)=>/^\d{2}:\d{2}$/.test(s)?Number(s.slice(0,2))*60+Number(s.slice(3)):NaN;
const clock=(m:number)=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
const validPlace=(p:any):p is Place=>p && typeof p.id==='string' && typeof p.name==='string' && p.name.length<=200 && typeof p.region==='string' && Number.isFinite(p.lat) && Math.abs(p.lat)<=90 && Number.isFinite(p.lon) && Math.abs(p.lon)<=180;

export default function DecisionLab(){
 const [drive,setDrive]=useState(60),[lead,setLead]=useState(24),[spread,setSpread]=useState(1.5),[wind,setWind]=useState(11),[missing,setMissing]=useState(false);
 const [from,setFrom]=useState('13:00'),[until,setUntil]=useState('19:00'),[date,setDate]=useState('');
 const [feedback,setFeedback]=useState(''),[calendarOpened,setCalendarOpened]=useState(false);
 const [places,setPlaces]=useState<Place[]>([]),[selected,setSelected]=useState<string|null>(null),[adding,setAdding]=useState(false);
 const [query,setQuery]=useState(''),[matches,setMatches]=useState<Place[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[searched,setSearched]=useState(false),[storageNote,setStorageNote]=useState('');
 const searchVersion=useRef(0);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(STORAGE)??'null');if(saved && Array.isArray(saved.places)){const list=saved.places.filter(validPlace).slice(0,30);setPlaces(list);setSelected(list.some((p:Place)=>p.id===saved.selected)?saved.selected:list[0]?.id??null);}}catch{setStorageNote('Lokationer kunne ikke indlæses på denne enhed.');}},[]);
 useEffect(()=>{setCalendarOpened(false);},[date,from,until,drive,selected]);
 const save=(list:Place[],id:string|null)=>{setPlaces(list);setSelected(id);try{localStorage.setItem(STORAGE,JSON.stringify({places:list,selected:id}));setStorageNote('');}catch{setStorageNote('Lokationen kan bruges nu, men kunne ikke gemmes på denne enhed.');}};
 const add=(place:Place)=>{save([place,...places.filter(p=>p.id!==place.id)].slice(0,30),place.id);setAdding(false);setQuery('');setMatches([]);setSearched(false);setFeedback('');};
 const search=async(e:React.FormEvent)=>{e.preventDefault();const version=++searchVersion.current;setBusy(true);setError('');setMatches([]);setSearched(false);try{const response=await fetch(`/api/locations?q=${encodeURIComponent(query.trim())}`);const data:any=await response.json();if(version!==searchVersion.current)return;if(!response.ok)throw new Error(data.error||'Søgningen mislykkedes.');setMatches((data.results??[]).filter(validPlace));setSearched(true);}catch(e){if(version===searchVersion.current)setError(e instanceof Error?e.message:'Prøv igen.');}finally{if(version===searchVersion.current)setBusy(false);}};
 const place=places.find(p=>p.id===selected);
 const result=useMemo(()=>{
  const score=windowScore({wind,direction:292.5,gust:missing?null:wind+2,wave:1.7,period:7,waveDirection:315},{windMin:8,windIdeal:11,windMax:15,gustMax:18,waveMin:.5,waveIdeal:1.7,waveMax:3,periodIdeal:7,directionIdeal:292.5,waveDirectionIdeal:315});
  const confidence=forecastConfidence({criticalComplete:!missing,fetchedAgeHours:1,runAgeHours:2,leadHours:lead,familyCount:3,windRange:spread,directionRange:10,timingSpreadHours:1,stableRuns:2,locallyValidated:false});
  const trip=tripWindow({earliestDeparture:minutes(from),latestReturn:minutes(until),windowStart:14*60,windowEnd:18*60,daylightEnd:19*60,outbound:drive,inbound:drive,rig:30,pack:20,minWater:90,maxDrive:180});
  return {score,confidence,trip,status:decision(score.score,confidence.label,trip.feasible,true)};
 },[drive,lead,spread,wind,missing,from,until]);
 const calendar=place&&result.trip.feasible?calendarLink({date,departure:result.trip.start-drive-30,home:result.trip.end+20+drive,waterStart:result.trip.start,waterEnd:result.trip.end,name:place.name,region:place.region,lat:place.lat,lon:place.lon}):null;
 const confidenceText={UNAVAILABLE:'Ukendt',LOW:'Lav',MEDIUM:'Middel',HIGH:'Høj'};
 const statuses:Record<string,string>={INSUFFICIENT_DATA:'Vi mangler vejrdata',NO_MATCH:'Turen passer ikke',WAIT:'Lovende — følg udviklingen',GO_CANDIDATE:'Turen ser lovende ud'};
 const inputClass='mt-2 h-12 min-w-0 max-w-full border-white/25 bg-white/5 text-base text-white';
 return <main className="min-h-screen bg-[#052a38] px-5 py-6 text-white sm:px-8"><div className="mx-auto max-w-3xl">
  <nav className="flex items-center justify-between"><a className="text-xl font-semibold tracking-tight" href="/">← Window</a><span className="rounded-full border border-amber-200/40 px-3 py-1 text-sm text-amber-100">Demo</span></nav>
  <a href="/ride" className="mt-5 block rounded-xl bg-cyan-200 p-4 font-semibold text-[#052a38]">Åbn sportsmotoren med rigtige prognoser →</a>
  <h1 className="mt-7 text-3xl font-semibold">Planlæg din tur</h1>
  <p className="mt-2 text-base text-cyan-100">Vælg et sted og se, hvor meget tid du får på vandet.</p>
  <section className="mt-6 rounded-2xl border border-white/20 p-5 sm:p-6" aria-labelledby="location-heading">
   <div className="flex flex-wrap items-center justify-between gap-3"><h2 id="location-heading" className="text-lg font-semibold">Hvor vil du kite?</h2>{places.length>0&&<Button variant="outline" className="border-white/30 bg-transparent text-white hover:bg-white/10 hover:text-white" onClick={()=>setAdding(!adding)} aria-expanded={adding}>{adding?'Luk søgning':'+ Tilføj lokation'}</Button>}</div>
   {places.length>0&&<div className="mt-4 flex flex-wrap gap-2">{places.map(p=><button key={p.id} type="button" onClick={()=>{save(places,p.id);setFeedback('');}} aria-pressed={p.id===selected} className={`min-h-11 rounded-full border px-4 py-2 text-base ${p.id===selected?'border-cyan-200 bg-cyan-200 text-[#052a38]':'border-white/25 hover:bg-white/10'}`}>{p.name}</button>)}</div>}
   {(adding||places.length===0)&&<div className="mt-4"><form onSubmit={search}><label htmlFor="place-search" className="text-sm text-cyan-100">Søg efter by eller område</label><div className="mt-2 flex gap-2"><Input id="place-search" value={query} minLength={2} maxLength={100} required placeholder="Fx Hanstholm eller Liseleje" className="h-12 min-w-0 border-white/25 bg-white/5 text-base text-white placeholder:text-slate-300" onChange={e=>{searchVersion.current++;setBusy(false);setQuery(e.target.value);setMatches([]);setError('');setSearched(false);}}/><Button type="submit" disabled={busy||query.trim().length<2} className="h-12 bg-cyan-200 px-5 text-[#052a38] hover:bg-cyan-100">{busy?'Søger…':'Søg'}</Button></div></form>
    <div aria-live="polite">{error&&<p className="mt-3 text-amber-100" role="alert">{error}</p>}{searched&&matches.length===0&&<p className="mt-3 text-cyan-100">Ingen steder fundet. Prøv en nærliggende by eller skriv land efter navnet.</p>}</div>
    {matches.length>0&&<ul className="mt-3 divide-y divide-white/15 rounded-xl border border-white/20">{matches.map(p=><li key={p.id}><button type="button" className="w-full p-4 text-left hover:bg-white/10" onClick={()=>add(p)}><span className="block font-semibold">{p.name}</span><span className="mt-1 block text-sm text-cyan-100">{p.region}</span><span className="mt-1 block text-sm text-cyan-200">Tilføj lokation</span></button></li>)}</ul>}
    <p className="mt-3 text-sm text-cyan-100">Steder fra <a href="https://open-meteo.com/" className="underline">Open-Meteo</a> / <a href="https://www.geonames.org/" className="underline">GeoNames</a>.</p>
   </div>}
   {place&&<div className="mt-4 flex flex-wrap items-start justify-between gap-2 text-sm"><p className="text-cyan-100">{place.region}<br/>Gemt på denne enhed.</p><button className="min-h-11 underline text-cyan-100" onClick={()=>{const next=places.filter(p=>p.id!==selected);save(next,next[0]?.id??null);setFeedback('');}}>Fjern lokation</button></div>}
   {storageNote&&<p role="status" className="mt-2 text-sm text-amber-100">{storageNote}</p>}
  </section>
  <section className="mt-4 rounded-2xl border border-white/20 p-5 sm:p-6" aria-labelledby="time-heading"><h2 id="time-heading" className="text-lg font-semibold">Hvornår har du tid?</h2><label className="mt-4 block min-w-0 text-sm">Dato<Input type="date" value={date} onChange={e=>setDate(e.target.value)} className={inputClass}/></label><div className="mt-4 grid grid-cols-2 gap-4"><label className="min-w-0 text-sm">Kan køre fra<Input type="time" value={from} onChange={e=>setFrom(e.target.value)} className={inputClass}/></label><label className="min-w-0 text-sm">Hjemme senest<Input type="time" value={until} onChange={e=>setUntil(e.target.value)} className={inputClass}/></label></div><label className="mt-5 block">Køretid én vej <span className="float-right font-semibold">{drive} min.</span><input aria-label="Køretid én vej" type="range" min="0" max="180" step="15" value={drive} onChange={e=>setDrive(+e.target.value)} className="mt-4 w-full accent-cyan-200"/></label><p className="mt-2 text-sm text-cyan-100">Dansk tid. Angiv selv køretiden til stedet.</p></section>
  <section className="mt-5 rounded-2xl bg-white p-5 text-slate-950 sm:p-6" aria-live="polite"><p className="text-sm font-medium text-slate-600">Eksempel på en tur{place?` · ${place.name}`:''}</p><h2 className="mt-2 text-2xl font-semibold">{statuses[result.status]}</h2>
   <p className="mt-3 text-base">{result.trip.feasible?`${clock(result.trip.start)}–${clock(result.trip.end)} på vandet · ${result.trip.waterMinutes} min.`:result.trip.reason}</p>
   <div className="my-5 grid grid-cols-2 gap-4 border-y border-slate-200 py-4"><div><p className="text-sm text-slate-600">Match med dine ønsker</p><p className="mt-1 text-3xl font-semibold">{result.score.score??'—'}<span className="text-base font-normal"> /100</span></p></div><div><p className="text-sm text-slate-600">Tillid til prognosen</p><p className="mt-1 text-2xl font-semibold">{confidenceText[result.confidence.label]}</p></div></div>
   <p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-950">Demovejr kl. 14–18. Lokationen er rigtig, men vejret og scoren er endnu ikke hentet for stedet eller datoen.</p>
   <div className="mt-5 border-t border-slate-200 pt-5"><h3 className="font-semibold">Gem en foreløbig tur</h3><p className="mt-2 text-sm text-slate-600">Kalenderen reserverer hele turen, inklusive kørsel. Tilføj fx en påmindelse 1 time før afgang i Google Calendar.</p>{calendar?<a className="mt-4 flex min-h-12 items-center justify-center rounded-lg bg-[#052a38] px-4 py-3 font-semibold text-white hover:bg-[#104455]" href={calendar} target="_blank" rel="noopener noreferrer" onClick={()=>setCalendarOpened(true)}>Åbn i Google Calendar</a>:<p className="mt-3 text-sm text-slate-600">Vælg en lokation, en dato og en tur med nok vandtid for at åbne kalenderen.</p>}<p className="mt-3 text-sm text-slate-600">{calendarOpened?'Kalenderen er åbnet. Tryk Gem dér — Window kan ikke se, om aftalen er gemt.':'Du gennemgår og gemmer selv aftalen i Google Calendar.'} Ændringer i Window opdaterer ikke kalenderen automatisk.</p></div>
   <details className="mt-4"><summary className="min-h-11 cursor-pointer py-2 font-medium">Hvorfor dette resultat?</summary><p className="mt-2">{result.confidence.reasons.join(' ')}</p><p className="mt-3 text-sm text-slate-600">30 min. klargøring, 20 min. nedpakning og mindst 90 min. på vandet. Samme dag, med demodagslys til kl. 19. Match er Window Score; tillid er Forecast Confidence, ikke en kalibreret procent.</p>{result.score.breakdown?<ul className="mt-3 space-y-2 text-sm">{Object.entries(result.score.breakdown).map(([k,v])=><li key={k}>{({wind:'Vind',direction:'Vindretning',gust:'Vindstød',wave:'Bølger',period:'Periode',waveDirection:'Bølgeretning'}[k])}: {v.toFixed(1)} point</li>)}</ul>:<p className="mt-3">{result.score.reasons.join(' ')}</p>}</details>
  </section>
  <div className="mt-4"><CalendarPanel draft={place&&calendar?{date,name:place.name,region:place.region,lat:place.lat,lon:place.lon,departure:result.trip.start-drive-30,home:result.trip.end+20+drive,waterStart:result.trip.start,waterEnd:result.trip.end}:null}/></div>
  <details className="mt-4 rounded-2xl border border-white/20 p-5"><summary className="cursor-pointer font-medium">Tilpas demo</summary><div className="mt-5 space-y-6">{[{label:'Vindstyrke',value:wind,set:setWind,min:5,max:20,step:1,unit:'m/s'},{label:'Timer til vejrvinduet',value:lead,set:setLead,min:12,max:168,step:12,unit:'timer'},{label:'Forskel mellem prognoser',value:spread,set:setSpread,min:0,max:8,step:.5,unit:'m/s'}].map(c=><label key={c.label} className="block text-base">{c.label} · {c.value} {c.unit}<input aria-label={c.label} type="range" min={c.min} max={c.max} step={c.step} value={c.value} onChange={e=>c.set(+e.target.value)} className="mt-3 w-full accent-cyan-200"/></label>)}<label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={missing} onChange={e=>setMissing(e.target.checked)} className="h-5 w-5 accent-cyan-200"/>Afprøv manglende vindstødsdata</label></div></details>
  <details className="mt-4 rounded-2xl border border-white/20 p-5"><summary className="cursor-pointer font-medium">Efter turen</summary><p className="mt-4">Var turen det værd?</p><div className="mt-3 flex flex-wrap gap-2">{['Ja','Nej','Tog ikke af sted'].map(x=><Button key={x} variant="outline" aria-pressed={feedback===x} className={feedback===x?'border-cyan-200 bg-cyan-200 text-[#052a38]':'border-white/30 bg-transparent text-white hover:bg-white/10 hover:text-white'} onClick={()=>setFeedback(x)}>{x}</Button>)}</div><p className="mt-3 text-sm text-cyan-100" role="status">{feedback?`Valgt: ${feedback}. Svaret gemmes ikke i demoen.`:'Demofeedback gemmes ikke.'}</p></details>
 </div></main>;
}
