'use client';
import {authFetch} from '@/lib/auth-fetch';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowUpRight,Compass,Waves,SlidersHorizontal,RefreshCw,Wind,ArrowDown} from 'lucide-react';
import WindowHeader from './window-header';
import SpotMap from './spot-map';
import {PLACES,EMPTY_USER,REGIONS,placesInRegion} from '@/lib/intelligence/catalog';
import {finite,geometry} from '@/lib/intelligence/engine';
import {validUser} from '@/lib/intelligence/validation';
import {spotResult,dayKey,time,direction,type Bundle,type SpotResult} from '@/lib/intelligence/explore';
import type {User} from '@/lib/intelligence/types';
import './explore.css';
const value=(n:number|null|undefined,unit:string)=>finite(n)?`${n.toFixed(1)} ${unit}`:'—';
const parameterNames:Record<string,string>={wind:'Vindstyrken',gust:'Vindstødene',swell:'Swellhøjden',period:'Bølgeperioden',swellBreakAngle:'Swellretningen mod kysten',windWave:'Vindbølgerne',windWavePeriod:'Vindbølgernes periode'};
const relative:Record<string,string>={onshore:'Påland · onshore','side-onshore':'Skrå påland · side-onshore','side-shore':'Sidevind · cross-shore','cross-offshore':'Skrå fraland · cross-offshore',offshore:'Fraland · offshore',unknown:'Kystvinkel ukendt'};
function planLink(result:SpotResult,day:string){const best=result.best;return '/ride?'+new URLSearchParams({spot:result.spot.id,date:day,...(best?{at:best.hour.validTime,sport:best.sport.id}: {})}).toString();}
function Detail({result,bundle,day,error,loading,initialSport,onRetry}:{initialSport?:string;result:SpotResult;bundle?:Bundle;day:string;error?:string;loading:boolean;onRetry:()=>void}){
 const {spot,best,hours,model}=result;
 const [sportId,setSportId]=useState(initialSport??'');
 const choices=[...new Map(result.options.map(o=>[o.sport.id,o.sport])).values()];
 const chosen=result.options.find(o=>o.sport.id===sportId)??best;
 const w=chosen?.hour.weather;const geo=geometry(w?.direction,spot.geometry.seaBearing);
 const timeline=[9,12,15,18,21].map(hour=>({hour,snapshot:hours.find(h=>Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Copenhagen',hour:'2-digit',hourCycle:'h23'}).format(new Date(h.validTime)))===hour)}));
 const link=planLink({...result,best:chosen},day);
 return <section className="spot-detail" id="spot-detail" aria-labelledby="spot-title"><div className="detail-heading"><div><p className="eyebrow">VALGT SPOT · {day}</p><h2 id="spot-title">{spot.name}</h2></div><a className="text-link" href={`https://www.openstreetmap.org/?mlat=${spot.lat}&mlon=${spot.lon}#map=14/${spot.lat}/${spot.lon}`} target="_blank" rel="noreferrer">Se lokation <ArrowUpRight size={17}/></a></div>
 {chosen?<><div className="window-summary"><div><p className="eyebrow">BEDSTE 2-TIMERS WINDOW</p><h3>{time(chosen.hour.validTime)}–{time(chosen.end)}</h3><p>{chosen.sport.name} · {chosen.sport.discipline}</p></div><div className="large-score">{chosen.score}<span>/100 fit</span></div></div>
 {choices.length>1&&<label className="discipline-select">Sammenlign disciplin <select value={chosen.sport.id} onChange={e=>setSportId(e.target.value)}>{choices.map(s=><option value={s.id} key={s.id}>{s.name} · {s.discipline}</option>)}</select></label>}
 <div className="conditions"><div><Wind size={20}/><span>Vind fra {direction(w?.direction)}</span><strong>{value(w?.wind,'m/s')}</strong><small>Vindstød {value(w?.gust,'m/s')}</small></div><div><Waves size={20}/><span>Swell fra {direction(w?.swellDirection)}</span><strong>{value(w?.swell,'m')}</strong><small>Periode {value(w?.period,'s')}</small></div><div><Compass size={20}/><span>Vind mod kysten</span><strong className="geometry-value">{relative[geo.relativeWind]}</strong><small>{geo.tack==='port'?'Bagbord':geo.tack==='starboard'?'Styrbord':'Side ukendt'} · foreløbig geometri</small></div></div>
 <div className="why"><h3>Hvorfor dette window?</h3><p>Bedste gennemsnitlige match over to sammenhængende timer. Begge timer er vurderet mod sportens grænser, lokale regler og dine gemte præferencer.</p><ul>{chosen.reasons.filter(r=>r.layer==='range'&&parameterNames[r.ruleId]).slice(0,3).map(r=><li key={r.ruleId}>{parameterNames[r.ruleId]} {r.points!==null&&r.points>=70?'ligger tæt på disciplinens foretrukne forhold.':'trækker ned i matchet med disciplinens foretrukne forhold.'}</li>)}{chosen.reasons.filter(r=>r.layer!=='range').map(r=><li key={r.ruleId}>{r.message}</li>)}</ul><p>Forecast confidence: <strong>{({UNAVAILABLE:'Kan ikke vurderes',LOW:'Lav',MEDIUM:'Middel',HIGH:'Høj'})[chosen.confidence.label]}</strong>. {chosen.confidence.reasons.join(' ')}</p></div>
 </>:<div className="empty-state"><h3>{loading&&!bundle?'Henter forhold…':result.tooFar?'Uden for din transportgrænse':error?'Forecast kunne ikke hentes':'Intet vurderbart 2-timers window'}</h3><p>{error??(result.tooFar?`${result.drive} min. én vej overstiger din gemte grænse.`:'Der kan mangle data, udstyr eller sammenhængende dagslystimer, eller forholdene passer ikke til de valgte regler.')}</p>{error&&<button className="secondary-action" onClick={onRetry}>Hent forecast igen <RefreshCw size={17}/></button>}</div>}
 <div className="timeline-heading"><h3>Forhold gennem dagen</h3><span>Dansk tid · samme model</span></div><div className="timeline-scroll"><table className="forecast-table"><caption className="sr-only">Forecast for {spot.name} {day}. Retninger angiver, hvor vind og swell kommer fra.</caption><thead><tr><th>Forhold</th>{timeline.map(t=><th key={t.hour}>{String(t.hour).padStart(2,'0')}.00</th>)}</tr></thead><tbody>{(['Vind','Vind fra','Vindstød','Swell','Swell fra','Periode','Tidevand'] as const).map(label=><tr key={label}><th scope="row">{label}</th>{timeline.map(({hour,snapshot:s})=><td key={hour}>{label==='Vind'?value(s?.weather.wind,'m/s'):label==='Vindstød'?value(s?.weather.gust,'m/s'):label==='Vind fra'?<Bearing degrees={s?.weather.direction}/>:label==='Swell fra'?<Bearing degrees={s?.weather.swellDirection}/>:label==='Swell'?value(s?.weather.swell,'m'):label==='Periode'?value(s?.weather.period,'s'):value(s?.weather.tide,'m')}</td>)}</tr>)}</tbody></table></div>
 <p className="data-note">{model?`Vind: ${model.id}. Swell: ECMWF WAM.`:'Ingen prognosemodel tilgængelig.'} — betyder manglende data. Swell er modeldata ude på havet, ikke målt bølgehøjde i brændingen. Frontside/backside kan ikke udledes sikkert uden lokal bølgeretning på selve bruddet.</p>
 <div className="detail-actions"><a className="primary-action" href={link}>{chosen?'Planlæg session / gem tur':'Åbn sessionplanlægger'} <ArrowUpRight size={18}/></a><a className="secondary-action" href={getForecastLink(spot.id)} onClick={()=>{const el=document.getElementById('spot-models');if(el&&getForecastLink(spot.id).startsWith('#'))(el as HTMLDetailsElement).open=true;}}>Detaljeret forecast</a></div>
 <details id="spot-models" className="source-details"><summary>Modeller, datagrundlag og lokale forbehold</summary><div className="timeline-scroll"><table className="forecast-table"><thead><tr><th>Model</th><th>Tid</th><th>Vind</th><th>Fra</th></tr></thead><tbody>{(bundle?.snapshots??[]).filter(s=>s.validTime===(chosen?.hour.validTime??hours[0]?.validTime)&&s.model!=='ecmwf_wam').map(s=><tr key={s.id}><td>{s.model}</td><td>{time(s.validTime)}</td><td>{value(s.weather.wind,'m/s')}</td><td>{direction(s.weather.direction)}</td></tr>)}</tbody></table></div><p>Retninger er fra-retninger. Spotgeometri er foreløbig. Fit er et match, ikke en sandsynlighed eller sikkerhedsgaranti. Transport: {result.drive===undefined?'ikke angivet':`${result.drive} min. én vej`}.</p>{spot.geometry.hazards.map(h=><p key={h}>{h}</p>)}{bundle?.warnings.length?<p>Nogle datakilder mangler: {bundle.warnings.join(' · ')}</p>:null}{chosen&&<ul>{chosen.reasons.filter(r=>r.layer==='range').map(r=><li key={r.ruleId}>{r.message}</li>)}</ul>}{spot.sourceUrl&&<p><a href={spot.sourceUrl} target="_blank" rel="noreferrer">Læs om spottet og lokale faciliteter ↗</a></p>}<p>Forecast: <a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Open-Meteo</a> / ECMWF, NOAA, DMI · CC BY 4.0.</p></details></section>;
}
function Bearing({degrees}:{degrees:number|null|undefined}){return finite(degrees)?<span className="bearing"><ArrowDown size={15} style={{transform:`rotate(${degrees}deg)`}} aria-hidden="true"/>{direction(degrees)}</span>:<>—</>;}
function getForecastLink(id:string){return ['agger-tange','hanstholm','mon-fyr','norre-vorupor'].includes(id)?`/forecast?spot=${encodeURIComponent(id)}`:'#spot-models';}
export default function Explore(){
 const [filter,setFilter]=useState('All'),[day,setDay]=useState(0),[region,setRegion]=useState('thy'),[selected,setSelected]=useState<string|null>(null),[bundles,setBundles]=useState<Record<string,Bundle>>({}),[errors,setErrors]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[reload,setReload]=useState(0),[now,setNow]=useState(0),[user,setUser]=useState<User>(EMPTY_USER),[profileState,setProfileState]=useState('loading');
 const [selectedDiscipline,setSelectedDiscipline]=useState('');
 const detailRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{const tick=()=>setNow(Date.now());tick();const timer=setInterval(tick,60000);authFetch('/api/rider').then(async r=>{if(!r.ok){setProfileState(r.status===401?'guest':'error');return;}const d=await r.json() as {profile?:unknown};if(validUser(d?.profile)){setUser(d.profile);if(d.profile.preferredRegion)setRegion(d.profile.preferredRegion);setProfileState('saved');}else setProfileState('empty');}).catch(()=>setProfileState('error'));return()=>clearInterval(timer);},[]);
 useEffect(()=>{let active=true;const controller=new AbortController();setLoading(true);setErrors({});setBundles({});async function load(){for(let i=0;i<PLACES.length&&active;i+=2){await Promise.all(PLACES.slice(i,i+2).map(async p=>{try{const r=await authFetch(`/api/intelligence?spot=${encodeURIComponent(p.id)}`,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(35000)])});const d=await r.json() as Bundle;if(!r.ok||!Array.isArray(d?.snapshots))throw new Error('Forecast utilgængeligt');if(active)setBundles(prev=>({...prev,[p.id]:d}));}catch{if(active)setErrors(prev=>({...prev,[p.id]:'Kunne ikke hente aktuelle forhold.'}));}}));}if(active)setLoading(false);}void load();return()=>{active=false;controller.abort();};},[reload]);
 const places=useMemo(()=>placesInRegion(region),[region]);
 const personal=user.sportIds.length>0,target=now?dayKey(now,day):'';
 const results=useMemo(()=>places.map(spot=>spotResult(spot,bundles[spot.id],user,filter,target,now)),[places,bundles,user,filter,target,now]);
 const ranked=[...results].sort((a,b)=>(b.best?.score??-1)-(a.best?.score??-1));
 const unavailable=!loading&&places.length>0&&places.every(p=>errors[p.id]&&!bundles[p.id]);
 function retry(){setNow(Date.now());setReload(n=>n+1);}
 const chosen=results.find(r=>r.spot.id===selected);
 function select(id:string,sportId=''){setSelectedDiscipline(sportId);setSelected(id);if(id===selected)detailRef.current?.scrollIntoView({behavior:'smooth',block:'start'});}
 useEffect(()=>{if(selected)detailRef.current?.scrollIntoView({behavior:'smooth',block:'start'});},[selected]);
 const progression=ranked.flatMap(r=>r.options.filter(o=>o.sport.id===user.progression?.sportId).map(o=>({result:r,option:o}))).sort((a,b)=>b.option.score-a.option.score)[0];
 const easy=ranked.find(r=>r.best&&r.best.score>=70&&r.best.sport.minimumLevel!=='experienced'&&finite(r.best.hour.weather.wind)&&finite(r.best.hour.weather.gust)&&r.best.hour.weather.wind>0&&r.best.hour.weather.gust/r.best.hour.weather.wind<=1.3&&finite(r.best.hour.weather.swell)&&r.best.hour.weather.swell<=1);
 return <div className="explore"><WindowHeader active="explore"/>
 <main className="explore-main"><div className="explore-heading"><div><p className="eyebrow">DIT NÆSTE WINDOW</p><h1>Hvor skal du på vandet?</h1></div><select aria-label="Område" value={region} onChange={e=>{setRegion(e.target.value);setSelected(null);}}>{REGIONS.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></div>
 <div className="explore-toolbar"><div className="sport-filters" aria-label="Sportsgren">{['All','Kite','Surf','Wing','Foil'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f==='All'?'Alle':f}</button>)}</div><div className="day-filters" aria-label="Dag">{['I dag','I morgen','Overmorgen'].map((d,i)=><button key={d} aria-pressed={day===i} onClick={()=>setDay(i)}>{d}</button>)}</div></div>
 <section className="top-pick" aria-label="Bedste match lige nu"><div><p className="eyebrow">BEDSTE MATCH · {['I DAG','I MORGEN','OVERMORGEN'][day]}</p>{ranked[0]?.best?<><h2>{ranked[0].best.sport.name} · {ranked[0].best.sport.discipline}</h2><p>{ranked[0].spot.name} · {time(ranked[0].best.hour.validTime)}–{time(ranked[0].best.end)} · {ranked[0].best.score}/100 fit · Forecastsikkerhed: {({UNAVAILABLE:'ukendt',LOW:'lav',MEDIUM:'middel',HIGH:'høj'})[ranked[0].best.confidence.label]}</p></>:<><h2>{loading?'Finder dit næste window…':unavailable?'Prognoserne er utilgængelige':'Intet match fundet'}</h2><p>{loading?'Prognoserne hentes for de valgte spots.':unavailable?'Vi kunne ikke hente aktuelle forhold. Prøv igen om lidt.':'Prøv en anden dag eller sportsgren, eller vælg et spot på kortet.'}</p></>}</div>{ranked[0]?.best?<button onClick={()=>select(ranked[0].spot.id)}>Se spot og forhold <ArrowUpRight size={17}/></button>:unavailable?<button onClick={retry}>Prøv igen <RefreshCw size={17}/></button>:null}</section>
 <SpotMap spots={places} selected={selected} onSelect={id=>select(id)} scores={Object.fromEntries(results.map(r=>[r.spot.id,r.best?.score??null]))} region={region}/>
 <div ref={detailRef} className="detail-anchor">{chosen&&<Detail key={`${selected}:${target}:${filter}:${selectedDiscipline}`} initialSport={selectedDiscipline} result={chosen} bundle={bundles[chosen.spot.id]} day={target} error={errors[chosen.spot.id]} loading={loading} onRetry={retry}/>}</div>
 <div className="list-heading"><h2>{personal?'Dine spots':'Spots i området'} <span>{places.length}</span></h2><p role="status">{loading?'Henter prognoser…':unavailable?'Aktuelle data mangler':`${ranked.filter(r=>r.best).length} spots med et match`}{!unavailable&&<button aria-label="Opdater forecast" onClick={retry} disabled={loading}><RefreshCw size={17}/></button>}</p></div>
 <div className="spot-list">{ranked.map(({spot,best,tooFar})=><button key={spot.id} className={`spot-card ${selected===spot.id?'active':''}`} onClick={()=>select(spot.id)} aria-pressed={selected===spot.id}><div className="spot-preview"><span className="preview-weather">{best?<><Wind size={19}/>{direction(best.hour.weather.direction)} · {value(best.hour.weather.wind,'m/s')}<br/><Waves size={19}/>{value(best.hour.weather.swell,'m')} · {value(best.hour.weather.period,'s')}</>:<><Compass size={23}/><span>Se spot og forhold</span></>}</span><span className="fit-score">{best?.score??'—'}<small>FIT</small></span></div><div><h3>{spot.name.replace(' · Agger Tange','')}</h3><p>{best?`${best.sport.name} · ${best.sport.discipline}`:tooFar?'Over din transportgrænse':errors[spot.id]??(loading?'Henter forecast…':'Intet match i dette tidsrum')}</p><span className="spot-card-time">{best?`${time(best.hour.validTime)}–${time(best.end)}`:'Se detaljer'} <ArrowUpRight size={17}/></span></div></button>)}</div>
 <div className="overview-note"><Compass size={20}/><p>{profileState==='loading'?'Henter din profil…':profileState==='error'?'Din profil kunne ikke hentes. Der vises standardmatch.':personal?'Fit bruger dine sportsgrene, dit niveau og dine regler. Udstyr filtrerer kun, hvis du har valgt det i profilen.':'Du ser standardmatch for en øvet rytter. Tilføj en profil for personlige windows.'} <a href="/ride#profile">Tilpas profil</a></p></div>
 <section className="session-picks" aria-label="Flere sessionforslag"><article><p className="eyebrow">BEDSTE PROGRESSION</p><h3>{user.progression?.goal||'Hvad vil du træne?'}</h3>{progression?<><p>{progression.result.spot.name} · match for din valgte disciplin. Øvelsesspecifik egnethed er ikke vurderet.</p><button onClick={()=>select(progression.result.spot.id,progression.option.sport.id)}>Se forhold <ArrowUpRight size={16}/></button></>:<a href="/ride#profile">{user.progression?'Intet match til målet · tilpas profil':'Vælg træningsmål i profilen'}</a>}</article><article><p className="eyebrow">LET / SJOV SESSION</p><h3>{easy?easy.spot.name:'Intet roligt match fundet'}</h3><p>70+ fit, begrænsede vindstød og højst 1 m swell, med tilgængelige bølgedata. Et forslag, ikke en sikkerhedsvurdering.</p>{easy&&<button onClick={()=>select(easy.spot.id)}>Se forhold <ArrowUpRight size={16}/></button>}</article></section>
 <footer><span>Window · Find forhold, der passer til dig.</span><a href="/forecast">DMI & detaljeret modelblik</a></footer></main></div>;
}
