'use client';
import {SPORTS} from '@/lib/intelligence/catalog';
import {hasEquipment,newId} from '@/lib/intelligence/engine';
import type {User} from '@/lib/intelligence/types';
const gearNames:Record<string,string>={kite:'Kite','kite-wave-board':'Waveboard / strapless board',twintip:'Twintip',kitefoil:'Kitefoil',surfboard:'Shortboard',longboard:'Longboard','surf-foil':'Surf foil',wing:'Wing',wingfoil:'Wingfoil board og foil','windsurf-rig':'Windsurfsejl og rig','windsurf-board':'Windsurfboard','windsurf-foil':'Windsurf foil',sup:'SUP-board',paddle:'Paddle','downwind-foil':'Downwind foil'};
export default function QuickProfile({profile,onChange,onContinue}:{profile:User;onChange:(p:User)=>void;onContinue:()=>void}){
 const sports=[...SPORTS,...profile.customSports],groups=[...new Set(sports.map(s=>s.name))];
 const selected=sports.filter(s=>profile.sportIds.includes(s.id));
 const needed=[...new Set(selected.flatMap(s=>s.equipmentKinds))];
 return <div className="quick-profile">
 <p className="ride-intro">Vælg dine sportsgrene og dit niveau. Det er nok til at få personlige forslag.</p>
 <fieldset><legend>1. Hvad vil du på vandet med?</legend><div className="sport-groups">{groups.map(name=>{const items=sports.filter(s=>s.name===name),count=items.filter(s=>profile.sportIds.includes(s.id)).length;return <details key={name} className="sport-group" open={count>0||undefined}><summary>{name}<span>{count?`${count} valgt`:'Vælg'}</span></summary><div className="discipline-choices"><button type="button" className="select-disciplines" onClick={()=>onChange({...profile,sportIds:count===items.length?profile.sportIds.filter(id=>!items.some(s=>s.id===id)):[...new Set([...profile.sportIds,...items.map(s=>s.id)])]})}>{count===items.length?'Fravælg alle':'Vælg alle discipliner'}</button>{items.map(s=><label key={s.id}><input type="checkbox" checked={profile.sportIds.includes(s.id)} onChange={e=>onChange({...profile,sportIds:e.target.checked?[...profile.sportIds,s.id]:profile.sportIds.filter(id=>id!==s.id)})}/><span>{s.discipline}{s.minimumLevel==='experienced'&&<small> · kræver erfaring</small>}</span></label>)}</div></details>;})}</div></fieldset>
 <fieldset><legend>2. Hvilket niveau passer til dig?</legend><div className="level-choices">{([{id:'beginner',label:'Begynder'},{id:'intermediate',label:'Øvet'},{id:'experienced',label:'Erfaren'}] as const).map(l=><label key={l.id} className={profile.level===l.id?'selected':''}><input type="radio" name="rider-level" value={l.id} checked={profile.level===l.id} onChange={()=>onChange({...profile,level:l.id})}/>{l.label}</label>)}</div><p className="ride-intro">Vælg det laveste niveau, hvis din erfaring varierer mellem sportsgrenene.</p></fieldset>
 <div className="profile-ready" role="status">{selected.length?`${selected.length} ${selected.length===1?'disciplin valgt':'discipliner valgt'}. ${profile.equipmentOnly?'Dit udstyrsfilter er aktivt.':'Du kan få forslag uden at registrere udstyr.'}`:'Vælg mindst én disciplin for at få forslag.'}</div>
 <button className="ride-button profile-continue" disabled={!selected.length} onClick={onContinue}>Videre til forslag</button><p className="ride-intro">Du kan prøve dine valg med det samme. Log ind, når du vil gemme profilen.</p>
 <details className="profile-extra"><summary>Mit udstyr · valgfrit</summary><p className="ride-intro">Tilføj udstyr, hvis du vil holde styr på det. Navne, størrelser og registrering er valgfrie.</p><label className="equipment-toggle"><input type="checkbox" checked={profile.equipmentOnly===true} onChange={e=>onChange({...profile,equipmentOnly:e.target.checked})}/><span>Vis kun forslag med mit registrerede udstyr</span></label>{profile.equipmentOnly&&<p className="ride-intro">Discipliner skjules, hvis deres udstyr ikke er registreret. Slå filteret fra for at se alle dine valgte discipliner.</p>}{needed.length>0&&<div className="gear-choices">{needed.map(kind=>{const has=profile.equipment.some(g=>g.kind===kind);return <label key={kind}><input type="checkbox" checked={has} onChange={e=>{if(e.target.checked)onChange({...profile,equipment:[...profile.equipment,{id:newId(),kind,name:gearNames[kind]??kind,size:null,sportIds:[]}]});else if(profile.equipment.filter(g=>g.kind===kind).every(g=>g.size===null&&g.name===(gearNames[kind]??kind))||window.confirm('Fjern det registrerede udstyr af denne type fra profilen?'))onChange({...profile,equipment:profile.equipment.filter(g=>g.kind!==kind)});}}/>{gearNames[kind]??profile.customSports.find(s=>s.id===kind)?.name??kind}</label>;})}</div>}{profile.equipmentOnly&&selected.some(s=>!hasEquipment(s,profile))&&<p className="gear-warning">Skjult af udstyrsfilteret: {selected.filter(s=>!hasEquipment(s,profile)).map(s=>`${s.name} ${s.discipline}`).join(', ')}.</p>}</details>
 </div>;
}
