'use client';
import {useEffect,useState} from 'react';
type Day={n:number;sum:number;ge:number[];directions:number[]};
export default function SeasonalWind({spotId,start,end}:{spotId:string;start:string;end:string}){
 const [days,setDays]=useState<Record<string,Day>|null>(null),[threshold,setThreshold]=useState(8),[error,setError]=useState('');
 useEffect(()=>{let active=true;setDays(null);setError('');if(!['agger-tange','hanstholm','mon-fyr','norre-vorupor'].includes(spotId)){setError('Historiske data for dette spot er endnu ikke tilføjet.');return;}fetch(`/history/${spotId}-daily.json`).then(async r=>{if(!r.ok)throw new Error();return r.json();}).then((d:any)=>{if(active)setDays(d.days);}).catch(()=>{if(active)setError('Historikken kunne ikke hentes.');});return()=>{active=false;};},[spotId]);
 const md=(time:number)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Copenhagen',month:'2-digit',day:'2-digit'}).format(time);
 const keys=new Set<string>();for(let t=Date.parse(start);t<=Date.parse(end)&&keys.size<31;t+=86400000)keys.add(md(t));keys.add(md(Date.parse(end)));
 const rows=days?[...keys].flatMap(k=>days[k]?[days[k]]:[]):[],n=rows.reduce((s,r)=>s+r.n,0),sum=rows.reduce((s,r)=>s+r.sum,0),ge=rows.reduce((s,r)=>s+r.ge[threshold],0),directions=Array.from({length:8},(_,i)=>rows.reduce((s,r)=>s+r.directions[i],0));
 return <details className="mt-5 rounded-2xl border border-white/20 p-5"><summary className="cursor-pointer text-lg font-semibold">Historiske forhold · samme kalenderdage 2016–2025</summary>{error?<p className="mt-3">{error}</p>:!n?<p className="mt-3">Henter historik…</p>:<><p className="mt-3">Gennemsnitlig vind: <strong>{(sum/n).toFixed(1)} m/s</strong> · hyppigste retning: {['N','NØ','Ø','SØ','S','SV','V','NV'][directions.indexOf(Math.max(...directions))]}</p><label className="mt-4 block">Vindgrænse · {threshold} m/s<input className="mt-3 w-full accent-cyan-200" aria-label="Historisk vindgrænse" type="range" min="0" max="30" value={threshold} onChange={e=>setThreshold(+e.target.value)}/></label><p className="mt-3">{(100*ge/n).toFixed(1)}% af {n.toLocaleString('da-DK')} gyldige timer havde mindst {threshold} m/s.</p><p className="mt-3 text-sm text-cyan-100">Alle døgnets timer på de valgte kalenderdage i dansk tid. ERA5-reanalyse via Open-Meteo; geografiske griddata. Dette er historisk forekomst, ikke sandsynligheden for at den aktuelle prognose holder. Bølgehistorik mangler.</p></>}</details>;
}
